/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class SI_Toko_Buah extends javax.swing.JFrame {

    /**
     * Creates new form SI_Toko_Buah
     */
    public SI_Toko_Buah() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        lbluserlogin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menufile = new javax.swing.JMenu();
        mn_datastok = new javax.swing.JMenuItem();
        mn_dataharga = new javax.swing.JMenuItem();
        mn_datapenjualan = new javax.swing.JMenuItem();
        mn_login = new javax.swing.JMenu();
        mnu_logout = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jInternalFrame1.setVisible(true);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\watermelon-4929429_640.png")); // NOI18N

        menufile.setText("File");
        menufile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menufileActionPerformed(evt);
            }
        });

        mn_datastok.setText("Data Stok");
        mn_datastok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_datastokActionPerformed(evt);
            }
        });
        menufile.add(mn_datastok);

        mn_dataharga.setText("Data Harga");
        mn_dataharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_datahargaActionPerformed(evt);
            }
        });
        menufile.add(mn_dataharga);

        mn_datapenjualan.setText("Data Penjualan");
        mn_datapenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_datapenjualanActionPerformed(evt);
            }
        });
        menufile.add(mn_datapenjualan);

        jMenuBar1.add(menufile);

        mn_login.setText("Login");
        mn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_loginMouseClicked(evt);
            }
        });
        jMenuBar1.add(mn_login);

        mnu_logout.setText("Log Out");
        mnu_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_logoutMouseClicked(evt);
            }
        });
        mnu_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_logoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnu_logout);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbluserlogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(lbluserlogin)
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrame1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menufileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menufileActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menufileActionPerformed

    private void mn_datahargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_datahargaActionPerformed
        // masuk ke halaman data harga
        Data_Harga_Buah n = new Data_Harga_Buah();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_mn_datahargaActionPerformed

    private void mn_datastokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_datastokActionPerformed
        // lanjut halam ke datastok
        Data_Stok_Buah n = new Data_Stok_Buah();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_mn_datastokActionPerformed

    private void mn_datapenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_datapenjualanActionPerformed
        // masuk kehalaman data penjualan
        Data_Penjualan n = new Data_Penjualan();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_mn_datapenjualanActionPerformed

    private void mnu_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_logoutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnu_logoutActionPerformed

    private void mnu_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_logoutMouseClicked
        // TODO add your handling code here:
        mnu_logout.setVisible(true);
        Exit n = new Exit();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnu_logoutMouseClicked

    private void mn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_loginMouseClicked
        // TODO add your handling code here:
        Login n = new Login();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_mn_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SI_Toko_Buah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SI_Toko_Buah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SI_Toko_Buah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SI_Toko_Buah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SI_Toko_Buah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbluserlogin;
    private javax.swing.JMenu menufile;
    private javax.swing.JMenuItem mn_dataharga;
    private javax.swing.JMenuItem mn_datapenjualan;
    private javax.swing.JMenuItem mn_datastok;
    private javax.swing.JMenu mn_login;
    private javax.swing.JMenu mnu_logout;
    // End of variables declaration//GEN-END:variables
}
